app/urls.py
from django.conf.urls import url
from . import views
app_name = 'app'
urlpatterns = [
    url(r'^register/',views.register,name='register'),
    url(r'^users/',views.use,name="users")
]


# <!-- {{form.as_p}}
# {% csrf_token %}
# <input id='but' type="submit" name="submit" class ='btn btn-outline-primary btn-lg lg' value="Register"> -->

stud/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include('app.urls')),
    url(r'^$',views.index,name='index'),
]

app/models.py
from django.db import models

# Create your models here.
class reg(models.Model):
    first = models.CharField(max_length=100)
    last = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    gender_choices = (
                      ('M','Male'),
                      ('F','Female'),
                      ('O','Other'),
                     )
    gender = models.CharField(max_length=1,choices=gender_choices,default='M')
    course_choices = (
    ('ECE','ECE'),
    ('CSE','CSE'),
    ('Mech','Mech'),
    ('Aero','Aero'),
    ('BioTech','BioTech'),
    )
    courses = models.CharField(max_length=10,choices=course_choices,default='CSE')
    def __str__(self):
        return self.first
        

app/forms.py
from django import forms
from . import models
class reg_form(forms.ModelForm):
    class Meta:
        model = models.reg
        fields = '__all__'

app/views.py
from django.shortcuts import render
from . import models,forms
# Create your views here.
def index(request):


    return render(request,'app/index.html',context={})

def register(request):
    form = forms.reg_form()
    if request.method == 'POST':

        form = forms.reg_form(request.POST)
        form.save()
        return index(request)


    return render(request,'app/register.html',context={'form':form})
def use(request):
      tab = models.reg.objects.all()

      return render(request,'app/users.html',context={'tab':tab})

templates/app/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome!</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static "app/index.css" %}">

  </head>
  <body style="background-image: url({% static "images/laptop.jpg" %});">

    <div class="container">
      <div class="jumbotron">
        <span class="amigo">Welcome Amigo!</span> <br> For Course Registration Click The <b>Button</b> Below
      </div>
      <hr color="yellow">
    </div>
    <a href="{% url "app:register" %}"> <button class="btn btn-outline-primary btn-lg " type="button" name="Register">Register Now</button> </a>
  </body>
</html>

templates/app/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Register</title>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:700" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "app/reg.css" %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">

  </script>
  <script src="{% static "app/reg.js" %}">

  </script>
  </head>
  <body style="background-image:url({% static "images/boat.jpg"%});background-repeat:no-repeat;background-size: cover;">
    <div class=''>
    <form class="form-group" action="" method="POST">
           {{form.as_p}}

     {% csrf_token %}
     <input type="submit" name="submit" class="btn btn-outline-primary btn-lg lg" >
   </form>

   </div>
  </body>
</html>

templates/app/users.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Users</title>
  </head>
  <body>

    {% for i in tab %}
<ul>
       <li>{{i.first}}</li>
       <li>{{i.last}}</li>
       <li>{{i.email}}</li>
       <li>{{i.gender}}</li>
       <li>{{i.courses}}</li>

</ul>
    {% endfor %}

  </body>
</html>